name: Publish documentation to GitHub Pages

on:
  push:
    tags:
      - '*'
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
          working-directory: '${{ github.workspace }}/docs'

      - name: Setup GitHub pages
        uses: actions/configure-pages@v4
        id: pages

      - name: Build documentation site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        working-directory: '${{ github.workspace }}/docs'
        env:
          JEKYLL_ENV: production

      - name: Upload documentation site
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_site/"

      - name: Deploy documentation site
        uses: actions/deploy-pages@v4
