name: Test

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  push:
    branches:
      - main

env:
  BATS_LIB_PATH: "./node_modules"

jobs:
  test-shell:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
          - macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install current Bash on macOS
        if: startsWith(matrix.os, 'macos-')
        run: brew install bash
      - uses: actions/setup-node@v3
      - run: npm install
      - run: git config --global user.name "Test user" && git config --global user.email "someone@example.com"
      - run: sudo apt-get install -y kcov
        if: matrix.os == 'ubuntu-latest'
      - name: Run Tests and Code Coverage on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: npm run test:coverage
      - name: Upload coverage reports to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: ./coverage
          fail_ci_if_error: true
      - name: Run Tests on other OSes
        if: matrix.os != 'ubuntu-latest'
        run: npm run test
